version: '3.8'

networks:
  default:
    external:
      name: eShopNetwork

services:
  catalog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - app_data:/app/data

volumes:
  app_data: